//
//  File.swift
//
//
//  Created by Rahul Kumar on 30/03/24.
//

import Foundation

public struct Country: Decodable, Identifiable {
    public var id = UUID()
    public let name: String
    public let dialCode: Int
    public let code, flag: String
}

extension Country {
    static let countries: [Country] = [
        Country(name: "Afghanistan", dialCode: 93, code: "AF", flag: "🇦🇫"),
        Country(name: "Åland Islands", dialCode: 358, code: "AX", flag: "🇦🇽"),
        Country(name: "Albania", dialCode: 355, code: "AL", flag: "🇦🇱"),
        Country(name: "Algeria", dialCode: 213, code: "DZ", flag: "🇩🇿"),
        Country(name: "American Samoa", dialCode: 1684, code: "AS", flag: "🇺🇸"),
        Country(name: "Andorra", dialCode: 376, code: "AD", flag: "🇦🇩"),
        Country(name: "Angola", dialCode: 244, code: "AO", flag: "🇦🇴"),
        Country(name: "Anguilla", dialCode: 1264, code: "AI", flag: "🇦🇮"),
        Country(name: "Antarctica", dialCode: 672, code: "AQ", flag: "🇦🇶"),
        Country(name: "Antigua and Barbuda", dialCode: 1268, code: "AG", flag: "🇦🇬"),
        Country(name: "Argentina", dialCode: 54, code: "AR", flag: "🇦🇷"),
        Country(name: "Armenia", dialCode: 374, code: "AM", flag: "🇦🇲"),
        Country(name: "Aruba", dialCode: 297, code: "AW", flag: "🇦🇼"),
        Country(name: "Australia", dialCode: 61, code: "AU", flag: "🇦🇺"),
        Country(name: "Austria", dialCode: 43, code: "AT", flag: "🇦🇹"),
        Country(name: "Azerbaijan", dialCode: 994, code: "AZ", flag: "🇦🇿"),
        Country(name: "Bahamas", dialCode: 1242, code: "BS", flag: "🇧🇸"),
        Country(name: "Bahrain", dialCode: 973, code: "BH", flag: "🇧🇸"),
        Country(name: "Bangladesh", dialCode: 880, code: "BD", flag: "🇧🇩"),
        Country(name: "Barbados", dialCode: 1246, code: "BB", flag: "🇧🇧"),
        Country(name: "Belarus", dialCode: 375, code: "BY", flag: "🇧🇾"),
        Country(name: "Belgium", dialCode: 32, code: "BE", flag: "🇧🇪"),
        Country(name: "Belize", dialCode: 501, code: "BZ", flag: "🇧🇿"),
        Country(name: "Benin", dialCode: 229, code: "BJ", flag: "🇧🇯"),
        Country(name: "Bermuda", dialCode: 1441, code: "BM", flag: "🇧🇲"),
        Country(name: "Bhutan", dialCode: 975, code: "BT", flag: "🇧🇹"),
        Country(name: "Bolivia, Plurinational State of", dialCode: 591, code: "BO", flag: "🇧🇴"),
        Country(name: "Bosnia and Herzegovina", dialCode: 387, code: "BA", flag: "🇧🇦"),
        Country(name: "Botswana", dialCode: 267, code: "BW", flag: "🇧🇼"),
        Country(name: "Bouvet Island", dialCode: 47, code: "BV", flag: "🏳"),
        Country(name: "Brazil", dialCode: 55, code: "BR", flag: "🇧🇷"),
        Country(name: "British Indian Ocean Territory", dialCode: 246, code: "IO", flag: "🇮🇴"),
        Country(name: "Brunei Darussalam", dialCode: 673, code: "BN", flag: "🇧🇳"),
        Country(name: "Bulgaria", dialCode: 359, code: "BG", flag: "🇧🇬"),
        Country(name: "Burkina Faso", dialCode: 226, code: "BF", flag: "🇧🇫"),
        Country(name: "Burundi", dialCode: 257, code: "BI", flag: "🇧🇮"),
        Country(name: "Cambodia", dialCode: 855, code: "KH", flag: "🇰🇭"),
        Country(name: "Cameroon", dialCode: 237, code: "CM", flag: "🇨🇲"),
        Country(name: "Canada", dialCode: 1, code: "CA", flag: "🇨🇦"),
        Country(name: "Cape Verde", dialCode: 238, code: "CV", flag: "🇨🇻"),
        Country(name: "Cayman Islands", dialCode: 1345, code: "KY", flag: "🇰🇾"),
        Country(name: "Central African Republic", dialCode: 236, code: "CF", flag: "🇨🇫"),
        Country(name: "Chad", dialCode: 235, code: "TD", flag: "🇹🇩"),
        Country(name: "Chile", dialCode: 56, code: "CL", flag: "🇨🇱"),
        Country(name: "China", dialCode: 86, code: "CN", flag: "🇨🇳"),
        Country(name: "Christmas Island", dialCode: 61, code: "CX", flag: "🇨🇽"),
        Country(name: "Cocos (Keeling) Islands", dialCode: 61, code: "CC", flag: "🇨🇨"),
        Country(name: "Colombia", dialCode: 57, code: "CO", flag: "🇨🇴"),
        Country(name: "Comoros", dialCode: 269, code: "KM", flag: "🇰🇲"),
        Country(name: "Congo", dialCode: 242, code: "CG", flag: "🇨🇬"),
        Country(name: "Congo, the Democratic Republic of the", dialCode: 243, code: "CD", flag: "🇨🇩"),
        Country(name: "Cook Islands", dialCode: 682, code: "CK", flag: "🇨🇰"),
        Country(name: "Costa Rica", dialCode: 506, code: "CR", flag: "🇨🇷"),
        Country(name: "Côte d'Ivoire", dialCode: 225, code: "CI", flag: "🇨🇮"),
        Country(name: "Croatia", dialCode: 385, code: "HR", flag: "🇭🇷"),
        Country(name: "Cuba", dialCode: 53, code: "CU", flag: "🇨🇺"),
        Country(name: "Cyprus", dialCode: 357, code: "CY", flag: "🇨🇾"),
        Country(name: "Czech Republic", dialCode: 420, code: "CZ", flag: "🇨🇿"),
        Country(name: "Denmark", dialCode: 45, code: "DK", flag: "🇩🇰"),
        Country(name: "Djibouti", dialCode: 253, code: "DJ", flag: "🇩🇯"),
        Country(name: "Dominica", dialCode: 1767, code: "DM", flag: "🇩🇲"),
        Country(name: "Dominican Republic", dialCode: 1809, code: "DO", flag: "🇩🇴"),
        Country(name: "Ecuador", dialCode: 593, code: "EC", flag: "🇪🇨"),
        Country(name: "Egypt", dialCode: 20, code: "EG", flag: "🇪🇬"),
        Country(name: "El Salvador", dialCode: 503, code: "SV", flag: "🇸🇻"),
        Country(name: "Equatorial Guinea", dialCode: 240, code: "GQ", flag: "🇬🇶"),
        Country(name: "Eritrea", dialCode: 291, code: "ER", flag: "🇪🇷"),
        Country(name: "Estonia", dialCode: 372, code: "EE", flag: "🇪🇪"),
        Country(name: "Ethiopia", dialCode: 251, code: "ET", flag: "🇪🇹"),
        Country(name: "Falkland Islands (Malvinas)", dialCode: 500, code: "FK", flag: "🇫🇰"),
        Country(name: "Faroe Islands", dialCode: 298, code: "FO", flag: "🇫🇴"),
        Country(name: "Fiji", dialCode: 679, code: "FJ", flag: "🇫🇯"),
        Country(name: "Finland", dialCode: 358, code: "FI", flag: "🇫🇮"),
        Country(name: "France", dialCode: 33, code: "FR", flag: "🇫🇷"),
        Country(name: "French Guiana", dialCode: 594, code: "GF", flag: "🇬🇫"),
        Country(name: "French Polynesia", dialCode: 689, code: "PF", flag: "🇵🇫"),
        Country(name: "French Southern Territories", dialCode: 262, code: "TF", flag: "🇹🇫"),
        Country(name: "Gabon", dialCode: 241, code: "GA", flag: "🇬🇦"),
        Country(name: "Gambia", dialCode: 220, code: "GM", flag: "🇬🇲"),
        Country(name: "Georgia", dialCode: 995, code: "GE", flag: "🇬🇪"),
        Country(name: "Germany", dialCode: 49, code: "DE", flag: "🇩🇪"),
        Country(name: "Ghana", dialCode: 233, code: "GH", flag: "🇬🇭"),
        Country(name: "Gibraltar", dialCode: 350, code: "GI", flag: "🇬🇮"),
        Country(name: "Greece", dialCode: 30, code: "GR", flag: "🇬🇷"),
        Country(name: "Greenland", dialCode: 299, code: "GL", flag: "🇬🇱"),
        Country(name: "Grenada", dialCode: 1473, code: "GD", flag: "🇬🇩"),
        Country(name: "Guadeloupe", dialCode: 590, code: "GP", flag: "🇬🇵"),
        Country(name: "Guam", dialCode: 1671, code: "GU", flag: "🇬🇺"),
        Country(name: "Guatemala", dialCode: 502, code: "GT", flag: "🇬🇹"),
        Country(name: "Guernsey", dialCode: 44, code: "GG", flag: "🇬🇬"),
        Country(name: "Guinea", dialCode: 224, code: "GN", flag: "🇬🇳"),
        Country(name: "Guinea-Bissau", dialCode: 245, code: "GW", flag: "🇬🇼"),
        Country(name: "Guyana", dialCode: 592, code: "GY", flag: "🇬🇾"),
        Country(name: "Haiti", dialCode: 509, code: "HT", flag: "🇭🇹"),
        Country(name: "Heard Island and McDonald Islands", dialCode: 672, code: "HM", flag: "🇭🇲"),
        Country(name: "Holy See (Vatican City State)", dialCode: 379, code: "VA", flag: "🇻🇦"),
        Country(name: "Honduras", dialCode: 504, code: "HN", flag: "🇭🇳"),
        Country(name: "Hong Kong", dialCode: 852, code: "HK", flag: "🇭🇰"),
        Country(name: "Hungary", dialCode: 36, code: "HU", flag: "🇭🇺"),
        Country(name: "Iceland", dialCode: 354, code: "IS", flag: "🇮🇸"),
        Country(name: "India", dialCode: 91, code: "IN", flag: "🇮🇳"),
        Country(name: "Indonesia", dialCode: 62, code: "ID", flag: "🇮🇩"),
        Country(name: "Iran, Islamic Republic of", dialCode: 98, code: "IR", flag: "🇮🇷"),
        Country(name: "Iraq", dialCode: 964, code: "IQ", flag: "🇮🇶"),
        Country(name: "Ireland", dialCode: 353, code: "IE", flag: "🇮🇪"),
        Country(name: "Isle of Man", dialCode: 44, code: "IM", flag: "🇮🇲"),
        Country(name: "Israel", dialCode: 972, code: "IL", flag: "🇮🇱"),
        Country(name: "Italy", dialCode: 39, code: "IT", flag: "🇮🇹"),
        Country(name: "Jamaica", dialCode: 1876, code: "JM", flag: "🇯🇲"),
        Country(name: "Japan", dialCode: 81, code: "JP", flag: "🇯🇵"),
        Country(name: "Jersey", dialCode: 44, code: "JE", flag: "🇯🇪"),
        Country(name: "Jordan", dialCode: 962, code: "JO", flag: "🇯🇴"),
        Country(name: "Kazakhstan", dialCode: 7, code: "KZ", flag: "🇰🇿"),
        Country(name: "Kenya", dialCode: 254, code: "KE", flag: "🇰🇪"),
        Country(name: "Kiribati", dialCode: 686, code: "KI", flag: "🇰🇮"),
        Country(name: "Korea, Democratic People's Republic of", dialCode: 850, code: "KP", flag: "🇰🇵"),
        Country(name: "Korea, Republic of", dialCode: 82, code: "KR", flag: "🇰🇷"),
        Country(name: "Kuwait", dialCode: 965, code: "KW", flag: "🇰🇼"),
        Country(name: "Kyrgyzstan", dialCode: 996, code: "KG", flag: "🇰🇬"),
        Country(name: "Lao People's Democratic Republic", dialCode: 856, code: "LA", flag: "🇱🇦"),
        Country(name: "Latvia", dialCode: 371, code: "LV", flag: "🇱🇻"),
        Country(name: "Lebanon", dialCode: 961, code: "LB", flag: "🇱🇧"),
        Country(name: "Lesotho", dialCode: 266, code: "LS", flag: "🇱🇸"),
        Country(name: "Liberia", dialCode: 231, code: "LR", flag: "🇱🇷"),
        Country(name: "Libya", dialCode: 218, code: "LY", flag: "🇱🇾"),
        Country(name: "Liechtenstein", dialCode: 423, code: "LI", flag: "🇱🇮"),
        Country(name: "Lithuania", dialCode: 370, code: "LT", flag: "🇱🇹"),
        Country(name: "Luxembourg", dialCode: 352, code: "LU", flag: "🇱🇺"),
        Country(name: "Macao", dialCode: 853, code: "MO", flag: "🇲🇴"),
        Country(name: "Macedonia, the Former Yugoslav Republic of", dialCode: 389, code: "MK", flag: "🇲🇰"),
        Country(name: "Madagascar", dialCode: 261, code: "MG", flag: "🇲🇬"),
        Country(name: "Malawi", dialCode: 265, code: "MW", flag: "🇲🇼"),
        Country(name: "Malaysia", dialCode: 60, code: "MY", flag: "🇲🇾"),
        Country(name: "Maldives", dialCode: 960, code: "MV", flag: "🇲🇻"),
        Country(name: "Mali", dialCode: 223, code: "ML", flag: "🇲🇱"),
        Country(name: "Malta", dialCode: 356, code: "MT", flag: "🇲🇹"),
        Country(name: "Marshall Islands", dialCode: 692, code: "MH", flag: "🇲🇭"),
        Country(name: "Martinique", dialCode: 596, code: "MQ", flag: "🇲🇶"),
        Country(name: "Mauritania", dialCode: 222, code: "MR", flag: "🇲🇷"),
        Country(name: "Mauritius", dialCode: 230, code: "MU", flag: "🇲🇺"),
        Country(name: "Mayotte", dialCode: 262, code: "YT", flag: "🇾🇹"),
        Country(name: "Mexico", dialCode: 52, code: "MX", flag: "🇲🇽"),
        Country(name: "Micronesia, Federated States of", dialCode: 691, code: "FM", flag: "🇫🇲"),
        Country(name: "Moldova, Republic of", dialCode: 373, code: "MD", flag: "🇲🇩"),
        Country(name: "Monaco", dialCode: 377, code: "MC", flag: "🇲🇨"),
        Country(name: "Mongolia", dialCode: 976, code: "MN", flag: "🇲🇳"),
        Country(name: "Montenegro", dialCode: 382, code: "ME", flag: "🇲🇪"),
        Country(name: "Montserrat", dialCode: 1664, code: "MS", flag: "🇲🇸"),
        Country(name: "Morocco", dialCode: 212, code: "MA", flag: "🇲🇦"),
        Country(name: "Mozambique", dialCode: 258, code: "MZ", flag: "🇲🇿"),
        Country(name: "Myanmar", dialCode: 95, code: "MM", flag: "🇲🇲"),
        Country(name: "Namibia", dialCode: 264, code: "NA", flag: "🇳🇦"),
        Country(name: "Nauru", dialCode: 674, code: "NR", flag: "🇳🇷"),
        Country(name: "Nepal", dialCode: 977, code: "NP", flag: "🇳🇵"),
        Country(name: "Netherlands", dialCode: 31, code: "NL", flag: "🇳🇱"),
        Country(name: "New Caledonia", dialCode: 687, code: "NC", flag: "🇳🇨"),
        Country(name: "New Zealand", dialCode: 64, code: "NZ", flag: "🇳🇿"),
        Country(name: "Nicaragua", dialCode: 505, code: "NI", flag: "🇳🇮"),
        Country(name: "Niger", dialCode: 227, code: "NE", flag: "🇳🇪"),
        Country(name: "Nigeria", dialCode: 234, code: "NG", flag: "🇳🇬"),
        Country(name: "Niue", dialCode: 683, code: "NU", flag: "🇳🇺"),
        Country(name: "Norfolk Island", dialCode: 672, code: "NF", flag: "🇳🇫"),
        Country(name: "Northern Mariana Islands", dialCode: 1670, code: "MP", flag: "🇲🇵"),
        Country(name: "Norway", dialCode: 47, code: "NO", flag: "🇳🇴"),
        Country(name: "Oman", dialCode: 968, code: "OM", flag: "🇴🇲"),
        Country(name: "Pakistan", dialCode: 92, code: "PK", flag: "🇵🇰"),
        Country(name: "Palau", dialCode: 680, code: "PW", flag: "🇵🇼"),
        Country(name: "Palestine, State of", dialCode: 970, code: "PS", flag: "🇵🇸"),
        Country(name: "Panama", dialCode: 507, code: "PA", flag: "🇵🇦"),
        Country(name: "Papua New Guinea", dialCode: 675, code: "PG", flag: "🇵🇬"),
        Country(name: "Paraguay", dialCode: 595, code: "PY", flag: "🇵🇾"),
        Country(name: "Peru", dialCode: 51, code: "PE", flag: "🇵🇪"),
        Country(name: "Philippines", dialCode: 63, code: "PH", flag: "🇵🇭"),
        Country(name: "Pitcairn", dialCode: 870, code: "PN", flag: "🇵🇳"),
        Country(name: "Poland", dialCode: 48, code: "PL", flag: "🇵🇱"),
        Country(name: "Portugal", dialCode: 351, code: "PT", flag: "🇵🇹"),
        Country(name: "Puerto Rico", dialCode: 1787, code: "PR", flag: "🇵🇷"),
        Country(name: "Qatar", dialCode: 974, code: "QA", flag: "🇶🇦"),
        Country(name: "Réunion", dialCode: 262, code: "RE", flag: "🇷🇪"),
        Country(name: "Romania", dialCode: 40, code: "RO", flag: "🇷🇴"),
        Country(name: "Russian Federation", dialCode: 7, code: "RU", flag: "🇷🇺"),
        Country(name: "Rwanda", dialCode: 250, code: "RW", flag: "🇷🇼"),
        Country(name: "Saint Barthélemy", dialCode: 590, code: "BL", flag: "🇧🇱"),
        Country(name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: 290, code: "SH", flag: "🇸🇭"),
        Country(name: "Saint Kitts and Nevis", dialCode: 1869, code: "KN", flag: "🇰🇳"),
        Country(name: "Saint Lucia", dialCode: 1758, code: "LC", flag: "🇱🇨"),
        Country(name: "Saint Martin (French part)", dialCode: 590, code: "MF", flag: "🇲🇫"),
        Country(name: "Saint Pierre and Miquelon", dialCode: 508, code: "PM", flag: "🇵🇲"),
        Country(name: "Saint Vincent and the Grenadines", dialCode: 1784, code: "VC", flag: "🇻🇨"),
        Country(name: "Samoa", dialCode: 685, code: "WS", flag: "🇼🇸"),
        Country(name: "San Marino", dialCode: 378, code: "SM", flag: "🇸🇲"),
        Country(name: "Sao Tome and Principe", dialCode: 239, code: "ST", flag: "🇸🇹"),
        Country(name: "Saudi Arabia", dialCode: 966, code: "SA", flag: "🇸🇦"),
        Country(name: "Senegal", dialCode: 221, code: "SN", flag: "🇸🇳"),
        Country(name: "Serbia", dialCode: 381, code: "RS", flag: "🇷🇸"),
        Country(name: "Seychelles", dialCode: 248, code: "SC", flag: "🇸🇨"),
        Country(name: "Sierra Leone", dialCode: 232, code: "SL", flag: "🇸🇱"),
        Country(name: "Singapore", dialCode: 65, code: "SG", flag: "🇸🇬"),
        Country(name: "Sint Maarten (Dutch part)", dialCode: 1721, code: "SX", flag: "🇸🇽"),
        Country(name: "Slovakia", dialCode: 421, code: "SK", flag: "🇸🇰"),
        Country(name: "Slovenia", dialCode: 386, code: "SI", flag: "🇸🇮"),
        Country(name: "Solomon Islands", dialCode: 677, code: "SB", flag: "🇸🇧"),
        Country(name: "Somalia", dialCode: 252, code: "SO", flag: "🇸🇴"),
        Country(name: "South Africa", dialCode: 27, code: "ZA", flag: "🇿🇦"),
        Country(name: "South Georgia and the South Sandwich Islands", dialCode: 500, code: "GS", flag: "🇬🇸"),
        Country(name: "South Sudan", dialCode: 211, code: "SS", flag: "🇸🇸"),
        Country(name: "Spain", dialCode: 34, code: "ES", flag: "🇪🇸"),
        Country(name: "Sri Lanka", dialCode: 94, code: "LK", flag: "🇱🇰"),
        Country(name: "Sudan", dialCode: 249, code: "SD", flag: "🇸🇩"),
        Country(name: "Suriname", dialCode: 597, code: "SR", flag: "🇸🇷"),
        Country(name: "Svalbard and Jan Mayen", dialCode: 47, code: "SJ", flag: "🇸🇯"),
        Country(name: "Swaziland", dialCode: 268, code: "SZ", flag: "🇸🇿"),
        Country(name: "Sweden", dialCode: 46, code: "SE", flag: "🇸🇪"),
        Country(name: "Switzerland", dialCode: 41, code: "CH", flag: "🇨🇭"),
        Country(name: "Syrian Arab Republic", dialCode: 963, code: "SY", flag: "🇸🇾"),
        Country(name: "Taiwan, Province of China", dialCode: 886, code: "TW", flag: "🇹🇼"),
        Country(name: "Tajikistan", dialCode: 992, code: "TJ", flag: "🇹🇯"),
        Country(name: "Tanzania, United Republic of", dialCode: 255, code: "TZ", flag: "🇹🇿"),
        Country(name: "Thailand", dialCode: 66, code: "TH", flag: "🇹🇭"),
        Country(name: "Timor-Leste", dialCode: 670, code: "TL", flag: "🇹🇱"),
        Country(name: "Togo", dialCode: 228, code: "TG", flag: "🇹🇬"),
        Country(name: "Tokelau", dialCode: 690, code: "TK", flag: "🇹🇰"),
        Country(name: "Tonga", dialCode: 676, code: "TO", flag: "🇹🇴"),
        Country(name: "Trinidad and Tobago", dialCode: 1868, code: "TT", flag: "🇹🇹"),
        Country(name: "Tunisia", dialCode: 216, code: "TN", flag: "🇹🇳"),
        Country(name: "Turkey", dialCode: 90, code: "TR", flag: "🇹🇷"),
        Country(name: "Turkmenistan", dialCode: 993, code: "TM", flag: "🇹🇲"),
        Country(name: "Turks and Caicos Islands", dialCode: 1649, code: "TC", flag: "🇹🇨"),
        Country(name: "Tuvalu", dialCode: 688, code: "TV", flag: "🇹🇻"),
        Country(name: "Uganda", dialCode: 256, code: "UG", flag: "🇺🇬"),
        Country(name: "Ukraine", dialCode: 380, code: "UA", flag: "🇺🇦"),
        Country(name: "United Arab Emirates", dialCode: 971, code: "AE", flag: "🇦🇪"),
        Country(name: "United Kingdom", dialCode: 44, code: "GB", flag: "🇬🇧"),
        Country(name: "United States", dialCode: 1, code: "US", flag: "🇺🇸"),
        Country(name: "Uruguay", dialCode: 598, code: "UY", flag: "🇺🇾"),
        Country(name: "Uzbekistan", dialCode: 998, code: "UZ", flag: "🇺🇿"),
        Country(name: "Vanuatu", dialCode: 678, code: "VU", flag: "🇻🇺"),
        Country(name: "Venezuela, Bolivarian Republic of", dialCode: 58, code: "VE", flag: "🇻🇪"),
        Country(name: "Viet Nam", dialCode: 84, code: "VN", flag: "🇻🇳"),
        Country(name: "Virgin Islands, British", dialCode: 1284, code: "VG", flag: "🇻🇬"),
        Country(name: "Virgin Islands, U.S.", dialCode: 1, code: "VI", flag: "🇻🇮"),
        Country(name: "Wallis and Futuna", dialCode: 681, code: "WF", flag: "🇼🇫"),
        Country(name: "Western Sahara", dialCode: 212, code: "EH", flag: "🇪🇭"),
        Country(name: "Yemen", dialCode: 967, code: "YE", flag: "🇾🇪"),
        Country(name: "Zambia", dialCode: 260, code: "ZM", flag: "🇿🇲"),
        Country(name: "Zimbabwe", dialCode: 263, code: "ZW", flag: "🇿🇼")
    ]
}

